### ISSUE TITLE
Code is not tested when PR is submitted

### ISSUE THREAD

**Issue by olenagerasimova** [Harvest-foundation/btcops#11]
I think we need to enable building and testing for our code in this repo when PR is submitted.

**Comment by g4s8** [comment]
@olenagerasimova fixed, see circleci is running on https://github.com/Harvest-foundation/btcops/pull/15

**Comment by 0crat** [comment]
Job [#11](https://github.com/harvest-foundation/btcops/issues/11) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
The job [#11](https://github.com/harvest-foundation/btcops/issues/11) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
