### ISSUE TITLE
Kill job after timeout

### ISSUE THREAD

**Issue by g4s8** [Harvest-foundation/btcops#5]
Issue: some peers may be very slow, blockchain downloading may take about 10 minutes from them, it would be better to restart the job in such cases.
The job should automatically terminate itself after timeout specified in environment variable `TIMEOUT` (millis).

**Comment by g4s8** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/Harvest-foundation/btcops/issues/5#issuecomment-434311473))

@g4s8 The user @g4s8[/z](https://www.0crat.com/u/g4s8) resigned from [#5](https://github.com/harvest-foundation/btcops/issues/5), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#5](https://github.com/harvest-foundation/btcops/issues/5) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CAWJH9K0X/fba3af63-e03b-40d2-8b4c-d0a6fa3fe2d2); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by g4s8** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/Harvest-foundation/btcops/issues/5#issuecomment-434337619))

@g4s8 The user @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) resigned from [#5](https://github.com/harvest-foundation/btcops/issues/5), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
The job [#5](https://github.com/harvest-foundation/btcops/issues/5) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/CAWJH9K0X/ad474e08-cd7c-4984-9bd5-2724432462e3); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#5](https://github.com/harvest-foundation/btcops/issues/5) is now out of scope

**Comment by ypshenychka** [comment]
@carlosmiranda I believe there was no work done by you in scope of this issue, right? So I will mark it as bad.

**Comment by carlosmiranda** [comment]
@ypshenychka yup. I haven't touched this, I think it's an outdated task.

**Comment by ypshenychka** [comment]
@carlosmiranda thanks

**Comment by ypshenychka** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
